name: Deploy to EC2 via Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 소스코드 체크아웃
        uses: actions/checkout@v4

      - name: JDK 17 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Gradle 빌드
        run: ./gradlew clean build

      - name: JAR 이름 통일 (app.jar로)
        run: |
          mkdir -p ./docker-output
          cp ./build/libs/*.jar ./docker-output/app.jar

      - name: Docker 이미지 빌드
        run: docker build -t gateway-app:latest .

      - name: Docker 이미지 저장 (.tar)
        run: |
          docker save gateway-app:latest -o ./docker-output/gateway-app.tar
          chmod 644 ./docker-output/gateway-app.tar

      - name: EC2로 Docker 이미지 전송
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: ./docker-output/gateway-app.tar
          target: /home/ubuntu/deploy/

      - name: EC2에서 컨테이너 실행
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/deploy/docker-output
            docker load < gateway-app.tar

            docker stop gateway-app || true
            docker rm gateway-app || true

            docker run -d --name gateway-app -p 8080:8080 gateway-app:latest